server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.tslgy.com/wushaodong/spring-cloud-microservice/
          username: wushaodong
          password: wushaodong
          search-paths: config-repo
