server:
  port: 8020
spring:
  application:
    name: microservice-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enable: true