server:
  port: 8010
spring:
  application:
    name: microservice-consumer-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true