server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TarryHoo/spring-cloud-microservice
          search-paths: config-repo
          username: wushaodong
          password: wushaodong
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/