server:
  port: 8021
spring:
  application:
    name: microservice-consumer-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: feign

ribbon:
  eureka:
    enable: true